/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IRandomNumberGeneratorV2,
  IRandomNumberGeneratorV2Interface,
} from "../IRandomNumberGeneratorV2";

const _abi = [
  {
    inputs: [],
    name: "getSRandomWord",
    outputs: [
      {
        internalType: "uint256",
        name: "_s_randomWord",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getSRandomWords",
    outputs: [
      {
        internalType: "uint256[]",
        name: "_s_randomWords",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getSRequestId",
    outputs: [
      {
        internalType: "uint256",
        name: "_s_requestId",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "requestRandomWords",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRandomNumberGeneratorV2__factory {
  static readonly abi = _abi;
  static createInterface(): IRandomNumberGeneratorV2Interface {
    return new utils.Interface(_abi) as IRandomNumberGeneratorV2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRandomNumberGeneratorV2 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IRandomNumberGeneratorV2;
  }
}
