/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IShoppingMall, IShoppingMallInterface } from "../IShoppingMall";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "name_",
        type: "string",
      },
      {
        internalType: "string",
        name: "symbol_",
        type: "string",
      },
    ],
    name: "createTenantSpaceNFT",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "rentTenantSpace",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IShoppingMall__factory {
  static readonly abi = _abi;
  static createInterface(): IShoppingMallInterface {
    return new utils.Interface(_abi) as IShoppingMallInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IShoppingMall {
    return new Contract(address, _abi, signerOrProvider) as IShoppingMall;
  }
}
