/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ITenantSpaceNFT,
  ITenantSpaceNFTInterface,
} from "../ITenantSpaceNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_tenant",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "_price",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_tenant",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_price",
        type: "uint256",
      },
    ],
    name: "setPrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITenantSpaceNFT__factory {
  static readonly abi = _abi;
  static createInterface(): ITenantSpaceNFTInterface {
    return new utils.Interface(_abi) as ITenantSpaceNFTInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITenantSpaceNFT {
    return new Contract(address, _abi, signerOrProvider) as ITenantSpaceNFT;
  }
}
