/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ITenantSpaceNFTFactory,
  ITenantSpaceNFTFactoryInterface,
} from "../ITenantSpaceNFTFactory";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "contract ITenantSpaceNFT",
        name: "tenantSpaceNFT",
        type: "address",
      },
    ],
    name: "TenantSpaceNFTCreated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "string",
        name: "symbol",
        type: "string",
      },
    ],
    name: "createTenantSpaceNFT",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITenantSpaceNFTFactory__factory {
  static readonly abi = _abi;
  static createInterface(): ITenantSpaceNFTFactoryInterface {
    return new utils.Interface(_abi) as ITenantSpaceNFTFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITenantSpaceNFTFactory {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ITenantSpaceNFTFactory;
  }
}
