/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { ShoppingMall, ShoppingMallInterface } from "../ShoppingMall";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "rentTenantSpaceNFT",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract ITenantSpaceNFT",
        name: "tenantSpaceNFT",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "storeTenantSpaceNFT",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061029b806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806360729c7c1461003b57806394014a481461006b575b600080fd5b61005560048036038101906100509190610134565b610089565b60405161006291906101c9565b60405180910390f35b610073610105565b60405161008091906101c9565b60405180910390f35b6000803390508373ffffffffffffffffffffffffffffffffffffffff166323b872dd8230866040518463ffffffff1660e01b81526004016100cc93929190610192565b600060405180830381600087803b1580156100e657600080fd5b505af11580156100fa573d6000803e3d6000fd5b505050505092915050565b600090565b60008135905061011981610237565b92915050565b60008135905061012e8161024e565b92915050565b6000806040838503121561014b5761014a610232565b5b60006101598582860161010a565b925050602061016a8582860161011f565b9150509250929050565b61017d816101e4565b82525050565b61018c81610228565b82525050565b60006060820190506101a76000830186610174565b6101b46020830185610174565b6101c16040830184610183565b949350505050565b60006020820190506101de6000830184610183565b92915050565b60006101ef82610208565b9050919050565b6000610201826101e4565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000819050919050565b600080fd5b610240816101f6565b811461024b57600080fd5b50565b61025781610228565b811461026257600080fd5b5056fea264697066735822122047cab030a68897fcc98fd48f12c2a7796d0bd897b915fb41f7e6baf49a6e161e64736f6c63430008070033";

type ShoppingMallConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ShoppingMallConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ShoppingMall__factory extends ContractFactory {
  constructor(...args: ShoppingMallConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "ShoppingMall";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ShoppingMall> {
    return super.deploy(overrides || {}) as Promise<ShoppingMall>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ShoppingMall {
    return super.attach(address) as ShoppingMall;
  }
  connect(signer: Signer): ShoppingMall__factory {
    return super.connect(signer) as ShoppingMall__factory;
  }
  static readonly contractName: "ShoppingMall";
  public readonly contractName: "ShoppingMall";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ShoppingMallInterface {
    return new utils.Interface(_abi) as ShoppingMallInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ShoppingMall {
    return new Contract(address, _abi, signerOrProvider) as ShoppingMall;
  }
}
