/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ShoppingMallInterface extends utils.Interface {
  contractName: "ShoppingMall";
  functions: {
    "createTenantSpaceNFT(string,string)": FunctionFragment;
    "rentTenantSpace()": FunctionFragment;
    "tenantSpaceNFTFactory()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createTenantSpaceNFT",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "rentTenantSpace",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tenantSpaceNFTFactory",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createTenantSpaceNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rentTenantSpace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tenantSpaceNFTFactory",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ShoppingMall extends BaseContract {
  contractName: "ShoppingMall";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ShoppingMallInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createTenantSpaceNFT(
      name_: string,
      symbol_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    rentTenantSpace(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tenantSpaceNFTFactory(overrides?: CallOverrides): Promise<[string]>;
  };

  createTenantSpaceNFT(
    name_: string,
    symbol_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  rentTenantSpace(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tenantSpaceNFTFactory(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    createTenantSpaceNFT(
      name_: string,
      symbol_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rentTenantSpace(overrides?: CallOverrides): Promise<BigNumber>;

    tenantSpaceNFTFactory(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    createTenantSpaceNFT(
      name_: string,
      symbol_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    rentTenantSpace(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tenantSpaceNFTFactory(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    createTenantSpaceNFT(
      name_: string,
      symbol_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    rentTenantSpace(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tenantSpaceNFTFactory(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
